[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "seamless_hpc"
version = "0.0.0"

[project.scripts]
greet = "seamlessHPC.__main__:main"

[tool.setuptools.packages.find]
where = ["."]